spring:
  kafka:
    bootstrap-servers: 10.0.50.103:9092
    producer:
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  rabbitmq:
    password: guest
    username: guest
    port: 5672
    addresses: 10.0.50.103
    #开启发送失败返回
    publisher-returns: true
    #开启发送确认
    publisher-confirms: true
    listener:
      simple:
        #指定最小的消费者数量
        concurrency: 2
        #指定最大的消费者数量
        max-concurrency: 2
        #开启ack
        acknowledge-mode: auto
      #开启ack
      direct:
        acknowledge-mode: auto
    #支持消息的确认与返回
    template:
      mandatory: true
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@10.0.52.7:1521:orcl
    username: SYS_NM_TEST
    password: TcH4P2AadnOi6x3HGE50SCmQwpu5640jSWVjOAeSawZglUDNc+AYDXtV3qQHli6XqSnyWDqIkFtLKcn7Ab5I0g==
    publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAItqdfGG8XYAkX59PE6R9PxFG5igPqs4xxj19VMd0jeeXPojJveMxoPLLKR1CONKRaNOxcu93P0PgY19FUCUEkcCAwEAAQ==

    #    driver-class-name: oracle.jdbc.driver.OracleDriver
    #    username: eep
    #    password: eep
    #    url: jdbc:oracle:thin:@192.168.0.219:1521:orcl

    druid:
      async-init: true
      initial-size: 15
      max-active: 30
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      validation-query: SELECT 1 FROM DUAL
      connection-properties: config.decrypt=true;config.decrypt.key=${spring.datasource.publicKey}
      filter:
        config:
          enabled: true

  redis:
    cluster:
      nodes: 10.0.50.103:7000,10.0.50.103:7001,10.0.50.103:7002,10.0.50.103:7003,10.0.50.103:7004,10.0.50.103:7005
    timeout: 6000ms
    lettuce:
      pool:
        max-active: 100
        max-wait: -1ms
        max-idle: 10
    database: 0
    #password: gjzspt@sofn

eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8880/eureka/


xxl:
  job:
    admin:
      addresses: http://10.0.50.103:8653/xxl-job-admin
    executor:
      appname: sys-job-executor
      port: 8651
      ip:
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
    accessToken:

proxy:
  user:
    username: share_api
    password: e10adc3949ba59abbe56e057f20f883e
