server:
  port: 8484
spring:
  main:
      allow-bean-definition-overriding: true
  application:
    name: bigdata-service
  profiles:
    active: local
    include: filter
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  mail:
    host: smtp.qq.com
    username: 1559285547@qq.com
    password: ztkefasuwamujgfa
management:
  server:
    servlet:
      context-path: /bigdata
    ssl:
      enabled: false


druid:
  pool:
    initialSize: 10
    maxActive: 100
    minIdle: 10


#mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  typeAliasesPackage: com.sofn.bigdata.model
  typeHandlersPackage: com.sofn.bigdata.convertor
  global-config:
    id-type: 3
    field-strategy: 2
    auto-set-db-type: true
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

eureka:
  instance:
    # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-renewal-interval-in-seconds: 10
    # 发呆时间，即服务续约到期时间（缺省为90s）
    lease-expiration-duration-in-seconds: 20
    prefer-ip-address: true
  client:
    healthcheck:
      # 开启健康检查（依赖spring-boot-starter-actuator）
      enabled: true
    fetch-registry: true
    register-with-eureka: true

logging:
  config: classpath:logback.xml

# swagger配置
swagger:
  # 扫描包
  base-package: com.sofn.bigdata.web
  # 名称
  name: 农业大数据平台
  # 接口前缀
  prefix: /bigdata

sofn:
  enableRemoveSpace:
    enable: false


http:
  maxTotal: 100
  defaultMaxPerRoute: 10
  connectTimeout: 1000
  connectionRequestTimeout: 500
  socketTimeout: 10000
  staleConnectionCheckEnabled: true


### IdWorker
idWorker:
  workId: 11
  dataCenterId: 11

#ribbon的超时时间
ribbon:
  ReadTimeout: 50000
  ConnectTimeout: 50000

#hive相关配置
hive:
  url: jdbc:hive2://192.168.21.101:10000/oracle
  driver-class-name: org.apache.hive.jdbc.HiveDriver
  type: com.alibaba.druid.pool.DruidDataSource
  user: hive
  password: 123456