spring:
  redis:
    database: 0
    host: 192.168.21.236
    port: 6379

eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://192.168.21.234:8880/eureka/


