server:
  port: 7999

spring:
  application:
    name: gateway-service

  redis:
    redisson:
      file: classpath:config/redisson-prod.yaml

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8880/eureka/

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

zuul:
  # 配置header过滤，设置空，避免Authorization信息丢失
  sensitive-headers:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  hystrix:
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 60000
  routes:
    sys-service: /sys/**
    flow-service: /flow/**
    aeem-service: /aeem/**

# swagger配置
swagger:
  # 扫描包
  base-package: com.sofn.gatewayservice.web
  # 名称
  name: 网关
  # 接口前缀
  prefix: