type: log
paths:
{{ range $i, $path := .paths }}
 - {{$path}}
{{ end }}
exclude_files: [".gz$"]

processors:
# Locale for timezone is only needed in non-json kelogs
- add_locale.when.not.regexp.message: "^{"
