--程栋 2018-3-9 资源申请新增 地方平台对接申请ID

alter table T_DGAP_RESOURCE_APPLICATION  add (LOCAL_PLATFORM_APPLI_ID varchar2(1000) );

comment on column T_DGAP_RESOURCE_APPLICATION.LOCAL_PLATFORM_APPLI_ID is '地方平台对接申请ID';

--程栋 2018-6-5 资源申请新增 起禁用状态
alter table T_DGAP_LOCAL_PLATFORM_APPLI add (ENABLE_STATUS varchar2(50) );
comment on column T_DGAP_LOCAL_PLATFORM_APPLI.ENABLE_STATUS is '起禁用状态(STARTED,STOPPED)';
comment on column T_DGAP_LOCAL_PLATFORM_APPLI.STATUS is '状态，可选值（NEW,APPLICATED,APPROVED,REJECTED）';

-- 何龙 2018-8-23 资源表增加通知接口标识
ALTER TABLE T_DGAP_RESOURCE
ADD (DATA_NOTIFIER VARCHAR2(50) DEFAULT 'none' NOT NULL);
COMMENT ON COLUMN T_DGAP_RESOURCE.DATA_NOTIFIER IS '通知接口标识';

--程栋 2018-8-29 预警规则表修改字段长度
ALTER TABLE T_DGAP_ALERT_CONFIG MODIFY (ALERT_TYPE VARCHAR2(32 CHAR) );

--程栋 2018-8-30 增加数据同步状态的表
CREATE TABLE T_DGAP_SYNC_DATE
(	"ID" VARCHAR2(64 CHAR) NOT NULL ENABLE,
"DATA" VARCHAR2(64 CHAR) NOT NULL ENABLE,
"LAST_SYNC_DATE" VARCHAR2(8 CHAR)
);
COMMENT ON COLUMN T_DGAP_SYNC_DATE.ID IS '主键';
COMMENT ON COLUMN T_DGAP_SYNC_DATE.DATA IS '对接数据的标识,有机:youji 绿色:lvse';
COMMENT ON COLUMN T_DGAP_SYNC_DATE.LAST_SYNC_DATE IS '最近一次成功数据同步发生的日期，格式YYYYMMDD';

--程栋 2018-9-7 T_DGAP_SYNC_DATE 增加字段
alter table T_DGAP_SYNC_DATE add (MARK varchar2(20) );
COMMENT ON COLUMN T_DGAP_SYNC_DATE.MARK IS '自增序列';

--程栋 2018-10-10 T_DGAP_LOCAL_PLATFORM_APPLI 增加地方平台对接管理表
DROP TABLE T_DGAP_LOCAL_PLATFORM_APPLI;
CREATE TABLE T_DGAP_LOCAL_PLATFORM_APPLI (
"ID" VARCHAR2(64 BYTE) NOT NULL ,
"PLATFORM_NAME" VARCHAR2(500 CHAR) NOT NULL ,
"PLATFORM_AREA_ID" VARCHAR2(64 CHAR) NOT NULL ,
"PLATFORM_LEVEL" VARCHAR2(50 CHAR) NOT NULL ,
"INDUSTRY" VARCHAR2(50 CHAR) NOT NULL ,
"URL" VARCHAR2(500 CHAR) NOT NULL ,
"NOTE" VARCHAR2(500 CHAR) NULL ,
"APPLICANT" VARCHAR2(64 CHAR) NOT NULL ,
"APPLICATION_TIME" DATE NULL ,
"APPLICATION_DEPARTMENT" VARCHAR2(500 CHAR) NULL ,
"AUDIT_USER_ID" VARCHAR2(64 CHAR) NULL ,
"AUDIT_TIME" DATE NULL ,
"AUDIT_COMMENTS" VARCHAR2(500 CHAR) NULL ,
"STATUS" VARCHAR2(50 CHAR) NOT NULL ,
"CREATE_TIME" DATE NOT NULL ,
"CREATE_BY" VARCHAR2(64 CHAR) NOT NULL ,
"UPDATE_TIME" DATE NULL ,
"UPDATE_BY" VARCHAR2(64 CHAR) NULL ,
"DEL_FLAG" VARCHAR2(7 BYTE) NOT NULL ,
"ENABLE_STATUS" VARCHAR2(50 BYTE) NULL
)
;
COMMENT ON TABLE "T_DGAP_LOCAL_PLATFORM_APPLI" IS '地方平台申请审核表';
COMMENT ON COLUMN "T_DGAP_LOCAL_PLATFORM_APPLI"."ID" IS 'ID';
COMMENT ON COLUMN "T_DGAP_LOCAL_PLATFORM_APPLI"."PLATFORM_NAME" IS '平台名称';
COMMENT ON COLUMN "T_DGAP_LOCAL_PLATFORM_APPLI"."PLATFORM_AREA_ID" IS '平台所属区域';
COMMENT ON COLUMN "T_DGAP_LOCAL_PLATFORM_APPLI"."PLATFORM_LEVEL" IS '平台级别，可选值（PROVINCE,CITY,COUNTY）';
COMMENT ON COLUMN "T_DGAP_LOCAL_PLATFORM_APPLI"."INDUSTRY" IS '平台行业，可选值（AGRICUTURE,HUSBANDRY,AQUACULTURE）';
COMMENT ON COLUMN "T_DGAP_LOCAL_PLATFORM_APPLI"."URL" IS '平台网址';
COMMENT ON COLUMN "T_DGAP_LOCAL_PLATFORM_APPLI"."NOTE" IS '备注';
COMMENT ON COLUMN "T_DGAP_LOCAL_PLATFORM_APPLI"."APPLICANT" IS '申请人';
COMMENT ON COLUMN "T_DGAP_LOCAL_PLATFORM_APPLI"."APPLICATION_TIME" IS '申请时间';
COMMENT ON COLUMN "T_DGAP_LOCAL_PLATFORM_APPLI"."APPLICATION_DEPARTMENT" IS '申请单位';
COMMENT ON COLUMN "T_DGAP_LOCAL_PLATFORM_APPLI"."AUDIT_USER_ID" IS '审核人';
COMMENT ON COLUMN "T_DGAP_LOCAL_PLATFORM_APPLI"."AUDIT_TIME" IS '审核时间';
COMMENT ON COLUMN "T_DGAP_LOCAL_PLATFORM_APPLI"."AUDIT_COMMENTS" IS '审核意见';
COMMENT ON COLUMN "T_DGAP_LOCAL_PLATFORM_APPLI"."STATUS" IS '状态，可选值（NEW,APPLICATED,APPROVED,REJECTED）';
COMMENT ON COLUMN "T_DGAP_LOCAL_PLATFORM_APPLI"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "T_DGAP_LOCAL_PLATFORM_APPLI"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "T_DGAP_LOCAL_PLATFORM_APPLI"."UPDATE_TIME" IS '修改时间';
COMMENT ON COLUMN "T_DGAP_LOCAL_PLATFORM_APPLI"."UPDATE_BY" IS '修改人';
COMMENT ON COLUMN "T_DGAP_LOCAL_PLATFORM_APPLI"."ENABLE_STATUS" IS '起禁用状态(STARTED,STOPPED)';


--程栋 2018-10-11 T_DGAP_LOCAL_PLATFORM_APPLI 增加字段
alter table T_DGAP_LOCAL_PLATFORM_APPLI add (DATANOTIFIER_URL varchar2(200) );
COMMENT ON COLUMN T_DGAP_LOCAL_PLATFORM_APPLI.DATANOTIFIER_URL IS '通知地址';


--程栋 2018-10-26 T_DGAP_RESOURCE T_DGAP_RESOURCE_DIRECTORY
-- 地方平台对接申请更改正式环境的资源目录id为特殊值  （这四个sql一定要按顺序执行）
alter table T_DGAP_RESOURCE_DIRECTORY disable primary key cascade;

UPDATE T_DGAP_RESOURCE SET DIRECTORY_ID='dfzsptdj-00000000000000000000000000000000000000000'
WHERE DIRECTORY_ID=(SELECT  "ID" FROM T_DGAP_RESOURCE_DIRECTORY  WHERE  "NAME"='地方平台对接') ;

UPDATE T_DGAP_RESOURCE_DIRECTORY SET "ID"='dfzsptdj-00000000000000000000000000000000000000000' WHERE "NAME"='地方平台对接';

alter table T_DGAP_RESOURCE_DIRECTORY enable primary key;
