apiVersion: v1
kind: Service
metadata:
  name: eureka
  labels:
    app: eureka
spec:
  clusterIP: None
  ports:
    - name: server
      port: 8880
      targetPort: 8880
  selector:
    app: eureka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka
  labels:
    app: eureka
spec:
  serviceName: eureka
  replicas: 3
  #Pod启停顺序管理
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      #当删除Pod时，等待时间
      terminationGracePeriodSeconds: 10
      containers:
        - name: eureka
          image: 10.0.52.21:5000/sofn/register-service:latest
          ports:
            - name: server
              containerPort: 8880
          env:
            - name: PROFILES
              value: k8s
            - name: APPID
              value: register
            - name: APP_NAME
              value: "register-service"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: APP_OPTS
              value: "
                     --spring.application.name=${APP_NAME}
                     --eureka.instance.hostname=${POD_NAME}.${APP_NAME}
                     --registerWithEureka=true
                     --fetchRegistry=true
                     --eureka.instance.preferIpAddress=false
                     --eureka.client.serviceUrl.defaultZone=http://eureka-0.${APP_NAME}:8880/eureka/,http://eureka-1.${APP_NAME}:8880/eureka/,http://eureka-2.${APP_NAME}:8880/eureka/
                     "
          resources:
            limits:
              cpu: 2000m
              memory: 1024Mi
            requests:
              cpu: 2000m
              memory: 1024Mi
