apiVersion: v1
kind: Service
metadata:
  name: eureka-nodeport
  labels:
    app: eureka-nodeport
spec:
  type: NodePort
  ports:
    - name: server
      port: 8880
      targetPort: 8880
      nodePort: 28880
  selector:
    app: eureka
