spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.21.129:3306/infor?characterEncoding=UTF-8&useUnicode=true&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456
    #publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKQtAC12Y5ptIlNtvEgAAaVz+a0y87PDDYcoEZB8Axxagt0SxRKeb/i6SsjjuUSVpPsR73uJ6J5U1ThgNALfo30CAwEAAQ==

    druid:
      async-init: true
      initial-size: 15
      max-active: 30
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      validation-query: SELECT 1 FROM DUAL
      #connection-properties: config.decrypt=true;config.decrypt.key=${spring.datasource.publicKey}
      filter:
        config:
          enabled: true

  redis:
    cluster:
      nodes: 10.0.50.103:7000,10.0.50.103:7001,10.0.50.103:7002,10.0.50.103:7003,10.0.50.103:7004,10.0.50.103:7005
    timeout: 6000ms
    lettuce:
      pool:
        max-active: 100
        max-wait: -1ms
        max-idle: 10
    database: 0

eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://10.0.50.101:8880/eureka/