apiVersion: apps/v1
kind: Deployment
metadata:
  name: sofn-sys
spec:
  selector:
    matchLabels:
      app: sofn-sys
  replicas: 1
  template:
    metadata:
      labels:
        app: sofn-sys
    spec:
      containers:
        - name: sofn-sys
          image: 10.0.52.21:5000/sofn/sys-service:latest
          ports:
            - containerPort: 7999
          env:
            - name: PROFILES
              value: dev
            - name: REGISTER_NAME
              value: "eureka"
            - name: APP_OPTS
              value: "
                     --spring.profiles.active=${PROFILES}
                     --eureka.client.serviceUrl.defaultZone=http://eureka-0.${REGISTER_NAME}:8880/eureka/,http://eureka-1.${REGISTER_NAME}:8880/eureka/,http://eureka-2.${REGISTER_NAME}:8880/eureka/
                     "