DECLARE appId  VARCHAR2(64) :='fyem';
BEGIN
	DELETE FROM SYS_TEST.SYS_SUBSYSTEM A WHERE A.APP_ID=appId;
	INSERT INTO SYS_TEST.SYS_SUBSYSTEM SELECT *  FROM SOFN.SYS_SUBSYSTEM A WHERE A.APP_ID=appId;

	DELETE FROM SYS_TEST.SYS_ROLE A WHERE A.SUBSYSTEM_ID in (SELECT A.id  FROM SOFN.SYS_SUBSYSTEM A WHERE A.APP_ID=appId);
	INSERT INTO SYS_TEST.SYS_ROLE SELECT *  FROM SOFN.SYS_ROLE A WHERE A.SUBSYSTEM_ID in (SELECT A.id  FROM SOFN.SYS_SUBSYSTEM A WHERE A.APP_ID=appId);

	DELETE FROM SYS_TEST.SYS_RESOURCE A WHERE A.APP_ID=appId;
	INSERT INTO SYS_TEST.SYS_RESOURCE SELECT *  FROM SOFN.SYS_RESOURCE A WHERE A.APP_ID=appId;
	DELETE FROM SYS_TEST.SYS_ROLE_RESOURCE B WHERE B.RESOURCE_ID IN (SELECT A.ID  FROM SOFN.SYS_RESOURCE A WHERE A.APP_ID=appId);
	INSERT INTO SYS_TEST.SYS_ROLE_RESOURCE SELECT * FROM SOFN.SYS_ROLE_RESOURCE B WHERE B.RESOURCE_ID IN (SELECT A.ID  FROM SOFN.SYS_RESOURCE A WHERE A.APP_ID=appId);

  -- DELETE FROM SYS_SYSTEM_ORG WHERE APP_ID=appId;
  -- INSERT INTO SYS_SYSTEM_ORG(ID,APP_ID,ORG_ID) VALUES(rawtohex(sys_guid()),appId,'sysorgroot');
END;
