apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  ports:
  - port: 7999
    targetPort: 7999
    nodePort: 30999
  type: NodePort
  selector:
    app: gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: 10.0.52.21:5000/sofn/gateway-service:latest
          ports:
            - containerPort: 7999
          env:
            - name: PROFILES
              value: dev
            - name: APPID
              value: register
            - name: REGISTER_NAME
              value: "eureka"
            - name: APP_OPTS
              value: "
                     --spring.profiles.active=${PROFILES}
                     --eureka.client.serviceUrl.defaultZone=http://eureka-0.${REGISTER_NAME}:8880/eureka/,http://eureka-1.${REGISTER_NAME}:8880/eureka/,http://eureka-2.${REGISTER_NAME}:8880/eureka/
                     "